CREATE TABLE banks (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    country VARCHAR2(100),
    applink VARCHAR2(255)
);


CREATE TABLE reviews (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_id NUMBER REFERENCES banks(id),
    review CLOB NOT NULL,
    review_text_clean CLOB,
    sentiment_label VARCHAR2(20),
    sentiment_score NUMBER,
    identified_theme VARCHAR2(50)
);
